# Exceptions
try:
    print(int("xx"))
except:
    print("tengo un error")